name: Build and publish to NPM
on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - uses: actions/upload-artifact@v2
        with:
          name: package-json
          path: package.json
  build:
    needs: publish-npm
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Remove existing package.json
        run: rm -f package.json
      - uses: actions/download-artifact@v2
        with:
          name: package-json
      - name: Install dependencies
        run: npm ci
      - name: Release prebuilt artifacts
        run: npx prebuild --all --runtime napi -u ${{ secrets.GITHUB_TOKEN }}
