name: Build all versions and publish to NPM
on: push
jobs:
  build:
    name: Build ${{ matrix.build-group }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: x64
            build-group: darwin-universal
    env:
      BUILD_GROUP: ${{ matrix.build-group }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: npm install
      - name: Prebuildify
        run: npm run prebuild-$BUILD_GROUP
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: prebuilds
          path: prebuilds/
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: prebuilds
          path: prebuilds
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
