name: Build all versions and publish to NPM
on:
  push:
    branches:
      - 'main'

jobs:
  Publish-NPM:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - uses: actions/upload-artifact@v2
        with:
          name: package-json
          path: package.json
  BuildAll:
    needs: Publish-NPM
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11 ]
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Remove existing package.json (Unix)
        if: ${{ runner.os != 'Windows' }}
        run: rm -f package.json
      - name: Remove existing package.json (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: Remove-Item "package.json" -ErrorAction Ignore
      - uses: actions/download-artifact@v2
        with:
          name: package-json
      - name: Install dependencies
        run: npm ci
      - name: Release prebuilt artifacts
        run: npx prebuild --all --runtime napi -u ${{ secrets.GITHUB_TOKEN }}
